name = "rober-m/ppp4-contracts-in-aiken"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'rober-m/ppp4-contracts-in-aiken'"

[repository]
user = "rober-m"
project = "ppp4-contracts-in-aiken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
